# Configuation

name: rasp2
domain: hass
period: 60

mqtt:
  address: 192.168.1.78
  port: 1883

adc:
  clk: 18
  miso: 23
  mosi: 24
  cs: 25

sensors:
  - type: am2302
    name: temperature
    pin: 4
  - type: switch
    name: switch1
    pin: 26
  - type: din
    name: motion
    pin: 7
  - type: ain
    name: light
    ch: 0
  - type: bmp085
    name: barometer
